# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Prepare SSH keys"
  when:
    - "gitlab_runner_ssh_public_key | default('') | length > 0"
    - "gitlab_runner_ssh_private_key | default('') | length > 0"
  block:
    - name: "Place SSH public key on the host for communicating with Runners."
      ansible.builtin.copy:
        src: "{{ gitlab_runner_ssh_public_key }}"
        dest: "{{ gitlab_runner_ssh_public_key_path }}"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "Place SSH private key on the host for communicating with Runners."
      ansible.builtin.copy:
        src: "{{ gitlab_runner_ssh_private_key }}"
        dest: "{{ gitlab_runner_ssh_private_key_path }}"
        owner: "root"
        group: "root"
        mode: "0600"

- name: "Create SSH key pair for communicating with Runners."
  community.crypto.openssh_keypair:  # noqa: args[module]
    path: "{{ gitlab_runner_ssh_private_key_path }}"
    type: "{{ gitlab_runner_ssh_key_type | default('ed25519') }}"
  register: "gitlab_runner_ssh_keypair"
  when: "not gitlab_runner_is_initial_dryrun"  # skip if run for the first time in check mode

- name: "Download and install container-linux-config-transpiler"
  ansible.builtin.get_url:
    url: "{{ gitlab_runner_transpiler_binary_url }}"
    dest: "/usr/local/bin/butane"
    mode: "0755"
    checksum: "{{ gitlab_runner_transpiler_binary_checksum }}"

- name: "Place the container linux configuration on the host"
  ansible.builtin.template:
    src: "flatcar-linux-config.bu.j2"
    dest: "/etc/gitlab-runner/flatcar-linux-config.bu"
    owner: "root"
    group: "root"
    mode: "0644"
  register: "flatcar_config_task"
  when: "not gitlab_runner_is_initial_dryrun"  # skip if run for the first time in check mode
  notify:
    - "Transpile the flatcar linux configuration"

- name: "Check if ignition.json is available and create it in any case"
  when: "not flatcar_config_task.changed"  # noqa no-handler
  ansible.builtin.stat:
    path: "/etc/gitlab-runner/ignition.json"
  register: "ignition_exists"
  changed_when: "not ignition_exists.stat.exists"
  notify:
    - "Transpile the flatcar linux configuration"

# This block is required to prepare for possible updates of the transpiler
# tool resulting in a different result. Also this helps to fix any kind of
# manual manipulation.
- name: "Check if ignition.json is up-to-date"
  when: "not flatcar_config_task.changed and ignition_exists.stat.exists"  # noqa no-handler
  block:
    - name: "Create temporary directory"
      ansible.builtin.tempfile:
        state: "directory"
        suffix: "ignition"
      register: "temp_directory"
      changed_when: false
      check_mode: false

    - name: "Dry-run of transpile the flatcar linux configuration"
      ansible.builtin.command: "butane -o {{ (temp_directory.path, 'ignition.json') | path_join }} /etc/gitlab-runner/flatcar-linux-config.bu"
      changed_when: false
      check_mode: false

    - name: "Stat temporary ignition.json file"
      ansible.builtin.stat:
        path: "{{ (temp_directory.path, 'ignition.json') | path_join }}"
      register: "temp_ignition_stats"
      changed_when:
        - "temp_ignition_stats.stat.checksum != ignition_exists.stat.checksum"
      check_mode: false
      notify:
        - "Transpile the flatcar linux configuration"

  always:
    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: "{{ temp_directory.path }}"
        state: "absent"
      changed_when: false
      check_mode: false
