# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Install GitLab-Runner dependencies"
  ansible.builtin.apt:
    pkg:
      - "debian-archive-keyring"
      - "apt-transport-https"
      - "gnupg"
      - "binutils"
    state: "present"
    update_cache: true

- name: "Install gitlab-runner via apt-get"
  when: "gitlab_runner_deb_file | length == 0"

  block:
    - name: "Add packages repository packages.gitlab.com/runner/gitlab-runner"
      ansible.builtin.deb822_repository:
        name: "gitlab-runner"
        types: "deb"
        uris: "https://packages.gitlab.com/runner/gitlab-runner/{{ ansible_facts.distribution | lower }}/"
        suites: "{{ ansible_facts.distribution_release }}"
        components: "main"
        signed_by: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
        state: "present"
        enabled: true

    - name: "Use APT pinning for Debian os"
      ansible.builtin.template:
        src: "pin-gitlab-runner.pref.j2"
        dest: "/etc/apt/preferences.d/pin-gitlab-runner.pref"
        owner: "root"
        group: "root"
        mode: '0644'
      when: "ansible_facts.distribution == 'Debian'"

    - name: "Install gitlab-runner-helper-images with downgrade option"
      ansible.builtin.apt:
        name: "{{ gitlab_runner_helper_images_package_name }}"
        state: "present"
        update_cache: true
        allow_downgrade: true
      when:
        - "not __gitlab_runner_is_initial_dryrun"  # skip if run for the first time in check mode
        - "gitlab_runner_version is version('17.7.0', 'ge') or gitlab_runner_version | length == 0"

    - name: "Install gitlab-runner with downgrade option"
      ansible.builtin.apt:
        name: "{{ gitlab_runner_package_name }}"
        state: "present"
        update_cache: true
        allow_downgrade: true
      when: "not __gitlab_runner_is_initial_dryrun"  # skip if run for the first time in check mode

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Install gitlab-runner manually using deb package"
  when:
    - "gitlab_runner_deb_file | length > 0"
    - "'gitlab-runner' not in ansible_facts.packages or
      ansible_facts.packages['gitlab-runner'][0].version is version(gitlab_runner_pkg_version, 'ne')"
  block:

    - name: "Install gitlab-runner-helper-images from a .deb file"
      ansible.builtin.apt:
        deb: "{{ gitlab_runner_helper_images_deb_file }}"
        allow_downgrade: true
      when: "gitlab_runner_version is version('17.7.0', 'ge') or gitlab_runner_version | length == 0"

    - name: "Install gitlab-runner from a .deb file"
      ansible.builtin.apt:
        deb: "{{ gitlab_runner_deb_file }}"
        allow_downgrade: true
      ignore_errors: "{{ ansible_check_mode }}"  # ignore errors due to unresolvable dependencies in check mode

...
