# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

galaxy_info:
  role_name: "redis"
  namespace: "hifis"
  author: "HIFIS Software Team"
  description: "Install and configure Redis"
  company: "Helmholtz Association"

  issue_tracker_url: "https://github.com/hifis-net/ansible-role-redis/issues"

  license: "Apache-2.0"

  min_ansible_version: "2.14"

  platforms:
    - name: "Ubuntu"
      versions:
        - "focal"
        - "jammy"

  galaxy_tags:
    - "redis"
    - "sentinel"
    - "cache"
    - "database"

dependencies: []

...
