# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-2.0-or-later

---

- name: 'Test apt-daily timer expression'
  become: true
  ansible.builtin.command:
    cmd: 'systemd-analyze calendar "{{ unattended_apt_daily_oncalendar }}"'
  register: '__apt_daily'
  changed_when: '__apt_daily.rc != 0'
  check_mode: false

- name: 'Test apt-daily-upgrade timer expression'
  become: true
  ansible.builtin.command:
    cmd: 'systemd-analyze calendar "{{ unattended_apt_daily_upgrade_oncalendar }}"'
  register: '__apt_daily_upgrade'
  changed_when: '__apt_daily_upgrade.rc != 0'
  check_mode: false

- name: 'Ensure directory apt-daily.timer.d exists'
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/system/apt-daily.timer.d'
    mode: '0755'
    state: 'directory'
    owner: 'root'
    group: 'root'

- name: 'Ensure directory apt-daily-upgrade.timer.d exists'
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/system/apt-daily-upgrade.timer.d'
    mode: '0755'
    state: 'directory'
    owner: 'root'
    group: 'root'

- name: 'Deploy apt-daily timer'
  become: true
  ansible.builtin.template:
    src: 'apt_daily_override.conf.j2'
    dest: '/etc/systemd/system/apt-daily.timer.d/schedule_override.conf'
    mode: '0644'
    owner: 'root'
    group: 'root'
  when:
    - '__apt_daily.rc == 0'
  notify:
    - 'Restart apt-daily timer'

- name: 'Deploy apt-daily-upgrade timer'
  become: true
  ansible.builtin.template:
    src: 'apt_daily_upgrade_override.conf.j2'
    dest: '/etc/systemd/system/apt-daily-upgrade.timer.d/schedule_override.conf'
    mode: '0644'
    owner: 'root'
    group: 'root'
  when:
    - '__apt_daily_upgrade.rc == 0'
  notify:
    - 'Restart apt-daily-upgrade timer'
...
