# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-2.0-or-later

---

- name: 'Remove apt-daily timer override'
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/system/apt-daily.timer.d/schedule_override.conf'
    state: 'absent'
  notify:
    - 'Restart apt-daily timer'

- name: 'Remove apt-daily-upgrade timer override'
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/system/apt-daily-upgrade.timer.d/schedule_override.conf'
    state: 'absent'
  notify:
    - 'Restart apt-daily-upgrade timer'
...
