# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
# SPDX-FileCopyrightText: Jan Vlnas
#
# SPDX-License-Identifier: GPL-2.0-or-later

---
galaxy_info:
  role_name: "unattended_upgrades"
  author: "hifis"
  description: "Setup unattended-upgrades on Debian-based systems"
  license: "GPLv2"
  min_ansible_version: "2.15"
  platforms:
    - name: "Ubuntu"
      versions:
        - "jammy"
        - "focal"
        - "noble"
    - name: "Debian"
      versions:
        - "bullseye"
        - "bookworm"

  galaxy_tags:
    - "system"

dependencies: []
