# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
gitlab_runner_version: ""

gitlab_runner_pkg_version: "{{ gitlab_runner_version + '-1' if gitlab_runner_version | length > 0 and gitlab_runner_version is version('16.9.0', 'ge') else gitlab_runner_version }}"

gitlab_runner_deb_file: ""

gitlab_runner_docker_machine_binary_url: "https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/releases/v0.16.2-gitlab.25/downloads/docker-machine-Linux-{{ ansible_facts.architecture }}"

gitlab_runner_docker_machine_binary_checksum: "sha256:04cc18c8f6ee0d71614064fa81116f20f3a37af53eeebf19bfb832ab9c46d3a0"

gitlab_runner_transpiler_binary_url: "https://github.com/coreos/butane/releases/download/v0.23.0/butane-{{ ansible_facts.architecture }}-unknown-linux-gnu"

gitlab_runner_transpiler_binary_checksum: "sha256:5833ce9f9c2932d9b02bc05821ffb6927d1e896a524c8dd53a4c9d2d90c47e2c"

gitlab_runner_install_docker: true

gitlab_runner_namerservers:
    - "9.9.9.9"
    - "149.112.112.112"

gitlab_runner_mtu: 1450

gitlab_runner_set_default_network_opts: false

gitlab_runner_config_path: "/etc/gitlab-runner/config.toml"

gitlab_runner_listen_address: ""

gitlab_runner_sentry_dsn: ""

gitlab_runner_list: []

gitlab_runner_insecure_registries: []

gitlab_runner_ssh_private_key_path: "/etc/gitlab-runner/gitlab_runner_key"
gitlab_runner_ssh_public_key_path: "/etc/gitlab-runner/gitlab_runner_key.pub"

gitlab_runner_enable_session_server: false
gitlab_runner_session_server_listen_address: "0.0.0.0:8093"
gitlab_runner_session_server_advertise_address: "{{ gitlab_runner_session_server_listen_address }}"
gitlab_runner_session_server_timeout: 1800

gitlab_runner_autoscaler_plugin_version: "v0.28.0"
gitlab_runner_autoscaler_binary_version: "{{ gitlab_runner_autoscaler_plugin_version | replace('v', '') }}"
gitlab_runner_autoscaler_plugin_url: "https://github.com/sardinasystems/fleeting-plugin-openstack/releases/download/{{ gitlab_runner_autoscaler_plugin_version }}/fleeting-plugin-openstack_{{ gitlab_runner_autoscaler_binary_version }}_linux_amd64.tar.gz"
gitlab_runner_autoscaler_plugin_checksumfile: "https://github.com/sardinasystems/fleeting-plugin-openstack/releases/download/{{ gitlab_runner_autoscaler_plugin_version }}/fleeting-plugin-openstack_{{ gitlab_runner_autoscaler_binary_version }}_sha512-checksums.txt"

gitlab_runner_butane_config_template: "butane-config.bu.j2"

# Do not display sensitive changes in diffs by default
gitlab_runner_hide_sensitive_changes: true
