# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  role_name: "gitlab"
  namespace: "hifis"
  author: "HIFIS Software Team"
  description: "Install and configure official GitLab Omnibus package"
  company: "Helmholtz Association"

  issue_tracker_url: "https://github.com/hifis-net/ansible-collection-toolkit/issues"

  license: "Apache-2.0"

  min_ansible_version: "2.14"

  platforms:
    - name: "EL"
      versions:
        - "8"
    - name: "Ubuntu"
      versions:
        - "bionic"
        - "focal"
        - "jammy"
    - name: "Debian"
      versions:
        - "bullseye"

  galaxy_tags:
    - "git"
    - "gitlab"
    - "omnibus"

dependencies: []

...
