# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

galaxy_info:
  role_name: "keepalived"
  namespace: "hifis"
  author: "HIFIS Software Team"
  description: "A role to set up Keepalived in a high availability and scalability context."
  company: "Helmholtz Association"

  issue_tracker_url: "https://github.com/hifis-net/ansible-collection-toolkit/issues"

  license: "Apache-2.0"
  min_ansible_version: "2.15"

  platforms:
    - name: "Ubuntu"
      versions:
        - "focal"
        - "jammy"
        - "noble"

  galaxy_tags:
    - "keepalived"
    - "vrrp"
    - "networking"

dependencies: []

...
