# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  role_name: "ssh_keys"
  author: "HIFIS Software Services"
  description: "Add provided authorized SSH public keys to a user."
  company: "Helmholtz Association"

  issue_tracker_url: "https://github.com/hifis-net/ansible-collection-toolkit/issues"

  license: "Apache-2.0"
  min_ansible_version: "2.17"

  platforms:
    - name: "EL"
      versions:
        - "8"
        - "9"
        - "10"
    - name: "Ubuntu"
      versions:
        - "jammy"
        - "noble"
    - name: "Debian"
      versions:
        - "bullseye"
        - "bookworm"
        - "trixie"

  galaxy_tags:
    - "ssh"
    - "authorized"
    - "key"
    - "keys"

dependencies: []

...
