name: "Ansible Lint check"
# visit https://github.com/marketplace/actions/ansible-lint for infos

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v3"

    - name: "Lint Ansible Playbook"
      uses: "ansible/ansible-lint-action@v6.3.0"
      with:
        targets: "."
