# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Check compliance with the REUSE specification"

on:
  push:
  pull_request:

jobs:
  reuse-lint:
    name: "REUSE compliance check"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v5"

      - name: "REUSE lint"
        uses: "fsfe/reuse-action@v6.0.0"
